#!/usr/bin/env python3
"""
Insert OSRM data into Index.html while preserving the original file encoding.
Also replaces distance functions to use OSRM lookup.
"""
import os

BASE = os.path.dirname(os.path.abspath(__file__))
INDEX = os.path.join(BASE, "Index.html")
OSRM  = os.path.join(BASE, "osrm_travel_data.js")

# --- Step 1: Detect original encoding ---
raw = open(INDEX, "rb").read()
# Check for BOM
if raw[:3] == b'\xef\xbb\xbf':
    print("WARNING: UTF-8 BOM detected, will be removed")
    raw = raw[3:]

# Try to detect: is it UTF-8 or Latin-1?
try:
    text = raw.decode("utf-8")
    enc = "utf-8"
    print(f"File is valid UTF-8 ({len(raw)} bytes)")
except UnicodeDecodeError:
    text = raw.decode("latin-1")
    enc = "latin-1"
    print(f"File is Latin-1 ({len(raw)} bytes)")

# Verify we can find known accented text
# The file uses box-drawing chars and accented French
test_patterns = ["MODÈLE", "═══", "données", "Patatoïde"]
for p in test_patterns:
    if p in text:
        print(f"  Found '{p}' - encoding OK")
    else:
        print(f"  NOT found '{p}' - checking alternative...")

# --- Step 2: Read OSRM data ---
osrm_raw = open(OSRM, "rb").read()
# OSRM file is UTF-8 (generated by Python)
osrm_text = osrm_raw.decode("utf-8")
if osrm_text.startswith('\ufeff'):
    osrm_text = osrm_text[1:]
print(f"OSRM data: {len(osrm_text)} chars, {osrm_text.count(chr(10))} lines")

# If original is latin-1, we need to convert OSRM UTF-8 chars to latin-1 compatible
# The OSRM comments have chars like === and accented letters
# Actually, the OSRM numeric data is pure ASCII, only comments have UTF-8
# Let's replace the comment line to use ASCII-safe version
osrm_text = osrm_text.replace(
    "/* \u2550\u2550\u2550 MATRICES TEMPS DE TRAJET OSRM (g\u00e9n\u00e9r\u00e9es automatiquement) \u2550\u2550\u2550 */",
    "/* === MATRICES TEMPS DE TRAJET OSRM (generees automatiquement) === */"
)
osrm_text = osrm_text.replace(
    "r\u00e9elle",
    "reelle"
)
osrm_text = osrm_text.replace(
    "g\u00e9n\u00e9r\u00e9es",
    "generees"
)

# --- Step 3: Find insertion point ---
# Insert after the CENTRE_TO_CIS closing "};", before "/* ... MODELE ISP ..."
marker = "'st laurent de cerdans':'st-laurent-cerdans','saint laurent de cerdans':'st-laurent-cerdans'"
marker_idx = text.find(marker)
if marker_idx == -1:
    print("ERROR: Could not find CENTRE_TO_CIS marker!")
    exit(1)

# Find the "};" that closes CENTRE_TO_CIS after the marker
close_idx = text.find("};", marker_idx)
if close_idx == -1:
    print("ERROR: Could not find closing '};'")
    exit(1)
insert_pos = close_idx + 2  # after "};"
print(f"Insertion point found at char offset {insert_pos}")

# --- Step 4: Build insertion block ---
cis_idx_line = "var CIS_IDX={};for(var _i=0;_i<CIS.length;_i++) CIS_IDX[CIS[_i].id]=_i;"
insertion = "\n\n" + cis_idx_line + "\n\n" + osrm_text + "\n"

# --- Step 5: Insert data ---
new_text = text[:insert_pos] + insertion + text[insert_pos:]
print(f"After insertion: {len(new_text)} chars")

# --- Step 6: Replace cisDistMin function ---
old_cisDistMin = """function cisDistMin(c1,c2){
  // Route P-O : facteur sinuosit\u00e9 1.2, vitesse moy 65 km/h (v\u00e9hicule perso)
  var km=cisDistKm(c1,c2);
  return Math.round(km*1.2/65*60);
}"""

new_cisDistMin = """function cisDistMin(c1,c2){
  /* Temps de trajet reel OSRM (lookup matrice pre-calculee) */
  var i1=CIS_IDX[c1.id], i2=CIS_IDX[c2.id];
  if(i1!==undefined && i2!==undefined) return Math.round(TRAVEL_CIS_MIN[i1][i2]);
  return Math.round(cisDistKm(c1,c2)*1.2/65*60);
}"""

# Try with the encoding-specific version of the accented chars
if old_cisDistMin in new_text:
    new_text = new_text.replace(old_cisDistMin, new_cisDistMin, 1)
    print("Replaced cisDistMin (Unicode version)")
else:
    # Try Latin-1 encoded version (the accented chars might be single bytes)
    # In Latin-1: e9=é
    old_latin = old_cisDistMin.encode("latin-1", errors="ignore").decode("latin-1")
    # Actually, let's search more flexibly
    search = "function cisDistMin(c1,c2){"
    idx = new_text.find(search)
    if idx == -1:
        print("ERROR: Could not find cisDistMin function!")
        exit(1)
    # Find the closing brace of this function
    # Count braces from the function start
    brace_count = 0
    end_idx = idx
    for i in range(idx, len(new_text)):
        if new_text[i] == '{':
            brace_count += 1
        elif new_text[i] == '}':
            brace_count -= 1
            if brace_count == 0:
                end_idx = i + 1
                break
    old_func = new_text[idx:end_idx]
    print(f"Found cisDistMin: '{old_func[:60]}...'")
    new_text = new_text[:idx] + new_cisDistMin + new_text[end_idx:]
    print("Replaced cisDistMin (brace-matching)")

# --- Step 7: Replace computeCommuneCoverage ---
# Find the function and replace nearestCis usage with COMMUNE_NEAREST
search_ccc = "function computeCommuneCoverage(ispState){"
idx_ccc = new_text.find(search_ccc)
if idx_ccc != -1:
    # Find end of function
    brace_count = 0
    end_ccc = idx_ccc
    for i in range(idx_ccc, len(new_text)):
        if new_text[i] == '{':
            brace_count += 1
        elif new_text[i] == '}':
            brace_count -= 1
            if brace_count == 0:
                end_ccc = i + 1
                break
    
    new_ccc = """function computeCommuneCoverage(ispState){
  /* Isochrones OSRM : COMMUNE_NEAREST donne le CIS le plus proche,
     TRAVEL_CIS_MIN donne les temps reels entre CIS pour le pool */
  var TRAVEL_RADIUS=20;
  var result=[];
  for(var i=0;i<COMMUNES.length;i++){
    var c=COMMUNES[i];
    var cn=COMMUNE_NEAREST[i];
    var cis=CIS[cn.c];
    /* Pool de ce CIS + CIS voisins (temps reel OSRM) */
    var pool=ispState[cis.id]||0;
    for(var j=0;j<CIS.length;j++){
      if(j!==cn.c && TRAVEL_CIS_MIN[j][cn.c]<=TRAVEL_RADIUS){
        pool+=(ispState[CIS[j].id]||0);
      }
    }
    var gh=0;
    for(var g=0;g<GARDE.length;g++){if(GARDE[g].cis===cis.id) gh=gardeHMois(GARDE[g].zone);}
    var cov=covPct(pool,gh);
    result.push({nom:c.n,lat:c.lat,lng:c.lng,cov:cov,cisNom:cis.nom,cisId:cis.id,pool:pool});
  }
  return result;
}"""
    new_text = new_text[:idx_ccc] + new_ccc + new_text[end_ccc:]
    print("Replaced computeCommuneCoverage")
else:
    print("WARNING: computeCommuneCoverage not found!")

# --- Step 8: Replace cisDistMin calls in computeRecruitWaves neighbor matrix ---
# Find "cisDistMin(CIS[i],CIS[j])<=TRAVEL_RADIUS" and replace with TRAVEL_CIS_MIN lookup
old_neighbor = "if(j!==i && cisDistMin(CIS[i],CIS[j])<=TRAVEL_RADIUS) nb.push(CIS[j].id);"
new_neighbor = "if(j!==i && TRAVEL_CIS_MIN[i][j]<=TRAVEL_RADIUS) nb.push(CIS[j].id);"
count = new_text.count(old_neighbor)
if count > 0:
    new_text = new_text.replace(old_neighbor, new_neighbor)
    print(f"Replaced {count} neighbor cisDistMin calls with TRAVEL_CIS_MIN lookup")

# Also replace in computeGreedyRecruitment
old_greedy = "if(j!==i && cisDistMin(CIS[i],CIS[j])<=travelRadius) nb.push(CIS[j].id);"
new_greedy = "if(j!==i && TRAVEL_CIS_MIN[i][j]<=travelRadius) nb.push(CIS[j].id);"
count2 = new_text.count(old_greedy)
if count2 > 0:
    new_text = new_text.replace(old_greedy, new_greedy)
    print(f"Replaced {count2} greedy cisDistMin calls with TRAVEL_CIS_MIN lookup")

# --- Step 9: Update section comment ---
old_comment_search = "DISTANCE / TEMPS TRAJET ENTRE CASERNES"
new_comment_text = "DISTANCE / TEMPS TRAJET ENTRE CASERNES (OSRM)"
if old_comment_search in new_text:
    new_text = new_text.replace(old_comment_search, new_comment_text, 1)
    print("Updated section comment")

# --- Step 10: Write file with SAME encoding as original ---
if enc == "utf-8":
    out_bytes = new_text.encode("utf-8")  # NO BOM
elif enc == "latin-1":
    # Need to ensure new content is latin-1 compatible
    try:
        out_bytes = new_text.encode("latin-1")
    except UnicodeEncodeError as e:
        print(f"WARNING: Cannot encode as Latin-1: {e}")
        print("Falling back to UTF-8 without BOM")
        out_bytes = new_text.encode("utf-8")

# Verify no BOM
if out_bytes[:3] == b'\xef\xbb\xbf':
    out_bytes = out_bytes[3:]

open(INDEX, "wb").write(out_bytes)
print(f"\nWritten {len(out_bytes)} bytes to Index.html (encoding: {enc}, no BOM)")
print(f"Line count: {new_text.count(chr(10)) + 1}")

# Final verification
verify = open(INDEX, "rb").read()
print(f"Verify: first 5 bytes = {list(verify[:5])}")
if verify[:3] == b'\xef\xbb\xbf':
    print("ERROR: BOM still present!")
else:
    print("OK: No BOM")
